% -------------------------------------------------------------------
%  Generated by MATLAB on 26-Mar-2021 21:28:43
%  MATLAB version: 9.4.0.813654 (R2018a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

x = saveVarsMat.x; % <1x1501 double> too many elements

clear saveVarsMat;
